development:
  adapter: redis
  url:  "redis://127.0.0.1:6379/1"
  channel_prefix: rails_test_production

test:
  adapter: redis
  url:  "redis://127.0.0.1:6379/1"
  channel_prefix: rails_test_production

production:
  adapter: redis
  url:  "redis://127.0.0.1:6379/1"
  channel_prefix: rails_test_production
